### ISSUE TITLE
Do you need more maintainers?

### ISSUE THREAD

**Issue by gilescope** [jethrogb/rust-reduce#6]
Happy to help maintain if possible? If I don't hear anything in a while I'll assume it's unmaintained and will forge on with my fork...

**Comment by gilescope** [comment]
For now will forge ahead with my fork.

**Comment by jethrogb** [comment]
Sorry I didn't respond! Somehow GitHub decided to not send my any emails about stuff going on in this repository... I'll try to review all issues & PRs during the upcoming holidays.
